config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :users
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route, optional: true
  has_many :wagons
  has_many :tickets
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
    end
  end

  private
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number, "Номер поезда" %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :route, "Маршрут" %>
    <%= f.collection_select :route_id, Route.all, :id, :title %>
   </div>  

  <div class="field">
  	<%= f.label :current_station, "Текущая станция" %>
  	<%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit "#{@train.new_record? ? 'Создать' : 'Редактировать'}" %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Показать', train %></td>
  <td><%= link_to 'Редактировать', edit_train_path(train) %></td>
  <td><%= link_to 'Удалить', train, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Редактирование поезда</h1>

<%= render 'form' %>

<%= link_to 'Показать', @train %> |
<%= link_to 'Назад', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Поезда</h1>

<table>
  <thead>
    <tr>
      <th>Номер</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Новый поезд', new_train_path %>
<%= link_to 'Назад', welcome_index_path %>

app/views/trains/new.html.erb
<h1>Новый поезд</h1>

<%= render 'form' %>

<%= link_to 'Назад', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер поезда:</strong>
  <%= @train.number %>
</p>
<p>
	<strong>Вагоны поезда:</strong>
	<% if @train.wagons.present? %>
		<p>Купейных вагонов</p>
		<%= @train.wagons.compartment.count %>
			<p>Мест верхних:</p>
				<% top_count = @train.wagons.compartment.map do |wagon| %>
				  <% wagon.top_seat.to_i %>
				<% end %> 
			<%= top_count.sum %> 
			<p>Мест нижних:</p>
				<% bottom_count = @train.wagons.compartment.map do |wagon| %>
				  <% wagon.bottom_seat.to_i %>
				<% end %> 
			<%= bottom_count.sum %>  
		<p>Плацкартных вагонов</p>
		<%= @train.wagons.econom.count %>
			<p>Мест верхних:</p>
				<% top_count = @train.wagons.econom.map do |wagon| %>
				  <% wagon.top_seat.to_i %>
				<% end %> 
			<%= top_count.sum %> 
			<p>Мест нижних:</p>
				<% bottom_count = @train.wagons.econom.map do |wagon| %>
				  <% wagon.bottom_seat.to_i %>
				<% end %> 
			<%= bottom_count.sum %> 		
	<% else %>
		У этого поезда ещё нет вагонов
	<% end %>		
</p>
<p>
	<strong>Маршрут:</strong>
	<% if @train.route.present? %>
		<%= @train.route.title %>
	<% else %>
		Маршрут не назначен
	<% end %>		
</p>
<p>
	<strong>На станции:</strong>
	<% if @train.current_station.present? %>
		<%= @train.current_station.title %>
	<% else %>
		Не указано
	<% end %>		
</p>

<%= link_to 'Редактировать', edit_train_path(@train) %> |
<%= link_to 'Назад', trains_path %>