config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :users
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'common/errors', resource: @user %>

  <div class="field">
    <%= f.label :name, "Имя пользователя" %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "#{@user.new_record? ? 'Создать' : 'Редактировать'}" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Редактирование пользователя</h1>

<%= render 'form' %>

<%= link_to 'Показать', @user %> |
<%= link_to 'Назад', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Пользователи</h1>

<table>
  <thead>
    <tr>
      <th>Имя пользователя</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Показать', user %></td>
        <td><%= link_to 'Редактировать', edit_user_path(user) %></td>
        <td><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый пользователь', new_user_path %>
<%= link_to 'Назад', welcome_index_path %>

app/views/users/new.html.erb
<h1>Новый пользователь</h1>

<%= render 'form' %>

<%= link_to 'Назад', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Имя пользователя:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Редактировать', edit_user_path(@user) %> |
<%= link_to 'Назад', users_path %>