config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :users
  resources :trains
  resources :railway_stations
  resources :routes
  resources :wagons
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :number, presence: true

  belongs_to :train, optional: true
  belongs_to :route, optional: true
  belongs_to :user, optional: true
  belongs_to :start_railway_station, class_name: "RailwayStation"
  belongs_to :finish_railway_station, class_name: "RailwayStation"
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
    end
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:number, :start_railway_station_id, :finish_railway_station_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <%= render 'common/errors', resource: @ticket %>

  <div class="field">
    <%= f.label :number, "ФИО пассажира" %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :start_railway_station, "Начальная станция" %>
    <%= f.collection_select :start_railway_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :finish_railway_station, "Конечная станция" %>
    <%= f.collection_select :finish_railway_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit "#{@ticket.new_record? ? 'Создать' : 'Редактировать'}" %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Редактировать билет</h1>

<%= render 'form' %>

<%= link_to 'Показать', @ticket %> |
<%= link_to 'Назад', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Билеты</h1>

<table>
  <thead>
    <tr>
      <th>Номер</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.number %></td>
        <td><%= link_to 'Показать', ticket %></td>
        <td><%= link_to 'Редактировать', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Удалить', ticket, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый билет', new_ticket_path %>
<%= link_to 'Назад', welcome_index_path %>

app/views/tickets/new.html.erb
<h1>Новый билет</h1>

<%= render 'form' %>

<%= link_to 'Назад', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ФИО пассажира:</strong>
  <%= @ticket.number %>
</p>

<p>
  <strong>Начальная станция:</strong>
  <%= @ticket.start_railway_station.title %>
</p>

<p>
  <strong>Конечная станция:</strong>
  <%= @ticket.finish_railway_station.title %>
</p>

<%= link_to 'Редактировать', edit_ticket_path(@ticket) %> |
<%= link_to 'Назад', tickets_path %>